# Need for a faster array Data Structure
We know how lists work in Python. We also know that lists can hold the data items of various data types. This means that the list storage allocated to elements can vary in size. This factor makes the array access slow, and operations on array could take long time. `numpy` provides a elagent solution in the form of `ndarray`, a $n$ - Dimensional collections of elements with same data types. `numpy` also provides easier way to manipulate arrays, This makes it High Performance Numerical Calculation possible.

## Importing `numpy`

Following is the standard statement to import numpy

In [1]:
import numpy as np

## Creating `ndarray` from Lists

`numpy` allows us to create an array from exsisting Python List. Datatype conversions are performed if nessasary

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

# Accessing array elements and random shuffeling

Array elements can be accessed using indices, slices and using masked arrays

Let's create a random array and then illustrate the methods of accessing array elements

In [5]:
x = np.arange(20)  # Like range(), but returns ndarry instead
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
x.shape # (rows,cols)

(20,)

In [8]:
x.shape = (4,5) # 4 rows 5 cols
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
np.random.shuffle(x) # shuffeles ndarray in-place
x

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [11]:
x[0]

array([15, 16, 17, 18, 19])

In [12]:
x[0][2]  # Ok, inefficient

17

In [13]:
x[0,2]   # Efficient

17

In [14]:
x[0,1:4]

array([16, 17, 18])

In [15]:
x[1:4,0]

array([ 5, 10,  0])

In [16]:
x > 15

array([[False,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

Note that it returned a boolean array after performing suitable operation. It is called masked array

In [17]:
x [ x > 15 ]

array([16, 17, 18, 19])

This method to access array element is called as Access by Masked array

## Functions that operates on `ndarray`s
Numpy provides many Mathematical functions, that not only operates on inividual numbers, but also on entire arrays. Let's illustrate them

In [18]:
np.sin(x)

array([[ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ]])

In [19]:
x[np.sin(x) > 0] # elements whose sine is non-negative

array([15, 19,  7,  8,  9, 13, 14,  1,  2,  3])

### `concatenate` the arrays

`concatenate((a1, a2, ...), axis=0)`
Join a sequence of arrays along an existing axis.

Parameters:	
   - `a1, a2`, ... : sequence of array_like
    
   - The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).
   - axis : int, optional
   - The axis along which the arrays will be joined. Default is 0.
   - Returns:	
   - res : ndarray
   - The concatenated array.
   
- `hstack((a1, a2, ...))` combines `a1, a2`, ... horizontally
- `vstack((a1, a2, ...))` combines `a1, a2`, ... vertically
- `dstack((a1, a2, ...))` combines `a1, a2`, ... depthwise

In [20]:
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])

In [21]:
a

array([1, 2, 3, 4])

In [22]:
b

array([9, 8, 7, 6])

In [25]:
np.concatenate((a,b),axis=0) # (a,b) is a tuple of arrays

array([1, 2, 3, 4, 9, 8, 7, 6])

In [28]:
np.dstack((a,b))

array([[[1, 9],
        [2, 8],
        [3, 7],
        [4, 6]]])

In [29]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [30]:
np.hstack((a,b))

array([1, 2, 3, 4, 9, 8, 7, 6])

We will use these functions frequenctly in upcomming chapters